# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare_projs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='uploaded_file_description',
        ),
        migrations.AddField(
            model_name='upload',
            name='file_author',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='upload',
            name='file_file',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='file_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
