# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare_projs', '0003_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
